#!/bin/sh

# INCLUDE THIS FILE ON YOUR .git/hooks 
# files on .git folder are not staged so you have to do this manually. thank you <3

STAGED_FILES=$(git diff --cached --name-only --diff-filter=ACM | grep ".jsx\{0,1\}$")
ESLINT="$(git rev-parse --show-toplevel)/node_modules/.bin/eslint"

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

PASS=true

printf "\nValidating Javascript:\n"

# Check if eslint is installed
if [[ ! -x "$ESLINT" ]]; then
  printf "\t\033[41mPlease install ESlint\033[0m (npm i --save-dev eslint)"
  exit 1
fi

if [[ "$STAGED_FILES" = "" ]]; then
  exit 0
fi

for FILE in $STAGED_FILES 
do
	$ESLINT "$FILE" --fix
	if [[ "$?" == 0 ]]; then
	    printf "\t\033[32mESLint Passed: \033[0m $FILE\n"
	else
	    printf "\t\033[41mESLint Failed: \033[0m $FILE\n"
	    PASS=false
	fi
	# Re-add files since they may have been fixed
	git add "$FILE"
done

if $PASS; then
  printf "\n\033[42mCOMMIT SUCCEEDED\033[0m\n"
else
  printf "\n\033[41mCOMMIT FAILED:\033[0m Fix eslint errors and try again\n"
  exit 1
fi

exit $?